_target_: src.models.aasist_module.AASISTLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001
  weight_decay: 0.0001

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.aasist.AASIST
  d_args:
    first_conv: 128
    filts: [70, [1, 32], [32, 32], [32, 64], [64, 64]]
    gat_dims: [64, 32]
    pool_ratios: [0.5, 0.7, 0.5, 0.5]
    temperatures: [2.0, 2.0, 100.0, 100.0]

# compile model for faster training with pytorch 2.0
compile: true
