_target_: src.models.aasistssl_module.AASISTSSLLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.000001
  weight_decay: 0.0001

scheduler: null

ssl_pretrained_path: /home/hungdx/code/xlsr2_300m.pt

# compile model for faster training with pytorch 2.0
compile: false
