_target_: src.models.aasistssl_layerwise_multiview_module.AASISTSSLLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001
  weight_decay: 0.0001

scheduler: null

net: null

ssl_pretrained_path: ${oc.env:XLSR_PRETRAINED_MODEL_PATH}
cross_entropy_weight: [0.1, 0.9] # weight for cross entropy loss 0.1 for spoof and 0.9 for bonafide
# compile model for faster training with pytorch 2.0
compile: true
