# https://neptune.ai

neptune:
  _target_: lightning.pytorch.loggers.neptune.NeptuneLogger
  api_key: ${oc.env:NEPTUNE_API_TOKEN} # api key is loaded from environment variable
  project: ${oc.env:NEPTUNE_PROJECT} # project name is loaded from environment variable
  # name: ""
  log_model_checkpoints: True
  prefix: ""
