defaults:
  - model_checkpoint
  #- early_stopping
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/loss"
  mode: "min"
  save_last: True
  auto_insert_metric_name: False
  save_top_k: 5 # save k best models (determined by above metric)
  #save_weights_only: True

early_stopping:
  monitor: "val/loss"
  patience: 20
  mode: "min"

model_summary:
  max_depth: -1
