defaults:
  - lora_checkpoint
  - early_stopping
  - rich_progress_bar
  - _self_
  - learning_rate_logger

learning_rate_logger:
  logging_interval: 'step'

lora_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/loss"
  mode: "min"
  save_last: True
  auto_insert_metric_name: False
  save_top_k: 5 # save k best models (determined by above metric)
  #save_weights_only: True

early_stopping:
  monitor: "val/loss"
  patience: 7
  mode: "min"

model_summary:
  max_depth: -1
